version: 43.0.9
pageUuid: d0019c5a-5fcf-11ed-804c-bbfb43acc53c
appTemplate:
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
      skipDepCycleCheckingEnabled: false
      serverDepGraphEnabled: false
      useRuntimeV2: false
  rootScreen: null
  version: 2.103.2
  markdownLinkBehavior: auto
