version: 43.0.9
pageUuid: d887b7da-1255-11ea-b589-d3d015525485
appTemplate:
  mobileAppSettings:
    object:
      mobileOfflineModeEnabled: false
  folders:
    - Temporary state
  experimentalPerfFeatures:
    object:
      serverDepGraphEnabled: false
      useRuntimeV2: false
  rootScreen: null
  version: 2.100.0
