version: 43.0.9
pageUuid: 3f2daa4a-5fc8-11ed-b4fc-c35f82abe481
appTemplate:
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
      skipDepCycleCheckingEnabled: false
      serverDepGraphEnabled: false
      useRuntimeV2: false
  rootScreen: null
  version: 2.103.2
  markdownLinkBehavior: auto
