version: 43.0.9
pageUuid: 1c807a72-6077-11ed-8212-a7f5719ae82d
appTemplate:
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
      skipDepCycleCheckingEnabled: false
      serverDepGraphEnabled: false
      useRuntimeV2: false
  rootScreen: null
  isGlobalWidget: true
  version: 2.103.2
  markdownLinkBehavior: auto
