version: 43.0.9
pageUuid: 63c12836-69ec-11ed-a33d-97c1e3d59e9d
appTemplate:
  experimentalPerfFeatures:
    object:
      batchCommitModelEnabled: false
      skipDepCycleCheckingEnabled: false
      serverDepGraphEnabled: false
      useRuntimeV2: false
  rootScreen: null
  version: 2.103.2
